apiVersion: v1
data:
    data.txt: ENC[AES256_GCM,data:bsKJssKwkOHN6N7FZIahl3gBC+Ps1R5Ebberolou8mFFnMvwKKE4n3Pn7SvF1Hy1a6e3Emoh7XwC0u1go9FC2ZZCPsw7GgVYN9LICrapp42rWEdHQPPE,iv:EBSc/EBRVwtYO2xxnY3fHJ+yxx3xmD+8jurzDGjB/Q0=,tag:iEuivgpjpQsX46fai1qV+Q==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: busyboxdata
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-29T16:43:44Z"
    mac: ENC[AES256_GCM,data:vY92hYdcRwR4GgjJQhbJQw0+zb9BaJm9KZGESx4oC/Vc6A2OVT0MjIHJloPdpX/sGucfFt7MYVHslhnAjodxtj3HodOy7fXQsZyNajzVhRquRBBkiKPdOs8Jef8yYGSmmNTCJrPs3ZGhxI0keRlwwnpliYWO0E/c7pwxuoA0Duk=,iv:pRAvMoefczC5Aaz7NAZhubL3K6rYSG2oe0VpIi18ipY=,tag:kLgSGYPB+07VQDMjvzR+mg==,type:str]
    pgp:
        - created_at: "2021-03-29T16:43:43Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/ZFgZfXuJNAQ/7BHK4O/cHy2Rydgf4DHtgLcrU0LZDkpmEGkTP5K2G6eeI
            gQ4ZlCas7Pz/wKghTpNqtXFs/Id925Qd55zXm7wX6nFPtuk4urU6cYiFWiaFEEPl
            E5uOxP9P6z53/WWxcpxwblfug9YCV58QERD2fxcfeQL6C+y4jS3WtUHHNwdmdexS
            1S0jJQPMHNC+UeZlunmuCiaPOjwgkyBFZcoayeyHNj/7Otn2owWdBDsPCpuswTAj
            bv71K+eklTZZPnAqHuVTyCKvuIw4PxvIzKmBo5jqLwDoI4PADHrVf4agf8LJ3tZF
            rFoyZnXoyXpSurlbdi5Ret98RhcX02w4nuQUGxKhD7LYh03S0fbiQ0mGND2DOGll
            V9UVWIwioJMJWaK9U2Ib1OO2GXpAW91S3Q922kj8h1eFGCfmdzbG4Bxktpr8kaRz
            PUPqM1//NQEE14SCgDk/uI+FqXJURDnbMxkchdQO78NcDataU3gtKaTVZoMat1LW
            766kqTVuIFKppWG6PTvjou6Jxddz7rSFld33MrGBqaXuRDrtrZKWwC764rviaybm
            u0fn50+sulq+Tv+kUVuHV0s4/xziSVH7JZrE2c3aNApH9saHvYI0AhkqtfdpesFC
            UlKNJSZP7riuUP5Lypo6NoH/iWRPUE+mLWWaHZzDfqnRNae1a1zovYl6LUcRoAfS
            XgFq/rslGONMuDOCNtcNYXRGrJG5KFrHafpMWYg2vzgzBC21QU43cjfZGyAHghgV
            5EARMAlRAAgjNwD0UhRBM1DkkKQwVsIGQ+WghPycVOu48lu61kOKsEJbycTtORo=
            =fha6
            -----END PGP MESSAGE-----
          fp: 041173C69061E4F841DD8E080650CAE18738112D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
