apiVersion: v1
data:
    data.txt: ENC[AES256_GCM,data:IN8FuKpGMULa2Yu7jIih1zempAbiD7u5DwXXhKKjGOeWhf72fCWSTdBJ4ELePdR0NfSJfVSjB0v43OdFjwZaP1yRmB6rEX2pfW3qz/VZEw+BS6ErMwOGJnkYCJBA,iv:8vbeCal8DbezOUD7dvIJSpe3X75ThsPB1L4/4/MDm24=,tag:ZjCXC1n2bHtBZ4OLgtWJ3Q==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: busyboxdata
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-30T13:56:30Z"
    mac: ENC[AES256_GCM,data:OHzogwhx99aNPrMvvZ42ncfumsFBLCjteYW/eNIIIQvLW9TnuKdj/XtSrHjKgXTxw1wyFImxHNDogV0ZtUuhK5tZ9tRvOin7dyL0FyjV/3aKaDRsnmnrjMmm97xxHJxAnntc5vlduPrkYOOiGEfi9Q/aS3FgGb0copgcLj/OmeA=,iv:DRkBe2U6ZB+zq0HWvUDRDXAg86MYLhhIg0T7TRtx9hY=,tag:FE0UA8ZAuJ576vXs/wrm7A==,type:str]
    pgp:
        - created_at: "2021-03-30T13:56:30Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAx/ZFgZfXuJNAQ//YN5/g1olZZaAk/yhAeJySAPgk7KvEh/xHCCwAOVv4mND
            gVudix7YHr862Wju043bmBNoE97nig3nYcFgZUGFl/XjOa9zEv6G3Bl0E1laW7BK
            wuAW9rZkcj4TPiCKho/oD3uWiWAapMOL/vyKfdXhD/JJaE56ZQAf6UwveFkS7tmB
            FjCnUhZ65ZymuyrJMiY7AzqCTP67LZ486JuOgasoqMB0zRYaydQzS5+ogKA9KAXV
            uqUEQ7XVj2aokf1vftYnGaDrHIrspDbehst2MstsNiw36o7vDwFpD+8UT7SE8Llx
            2vhkPZGG3ufResBXSSgDnbxXIEghWFpIIETxSFU5OKz+YQhdgZy+YG68B9bs98FB
            ebEsa+v/nnTY+3lOELZWlbvtHQLo+H31C2as0cycqT8eAnD7yf2P60++sbHdSAmE
            g6RcOWAETbSjPyaY66wBqGE0Aomsr90Kcxr+wMl0n4SnsNgmzoueNrXs0VQXJWTQ
            iolyzDyCqSy4ZVK9o9HtB6Yy3t1aBrLPveesiMrgKhPTGU3pRtCAHnXVJPeIjMVB
            gaZ2bWjH5Y3DX++Hw9CDSyRmaN0i7MxLwmaWLRy/kuAw4kdtQqCkRQKOHQiWqzs6
            OxqqG+pw7815cG1/5i1CJsjiug6mnxf+aGSlYk+LJF3AJ9Wiq7mIELEDMqAs27fS
            XAFUP0JPoY0RpFgpCPD9f4lAFOLpyWixoN/bVLg4ZNaSAL35AAqu2z/XWe7dEpIF
            rB2c/EpvyvCG+4zYJ6kr6j5Emc/2MvOPubsuVPj0jDor1oSNC2YfWfrR8nJU
            =H7s+
            -----END PGP MESSAGE-----
          fp: 041173C69061E4F841DD8E080650CAE18738112D
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
