---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: busyboxconfigmap
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-gpg
  interval: 5m0s
  path: ./apps/kustomize/test1/busybox
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  validation: client

