---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: busybox
  namespace: flux-system
spec:
  chart:
    spec:
      chart: ./apps/base/charts/busybox/
      sourceRef:
        kind: GitRepository
        name: podinfo
  interval: 10m0s
  targetNamespace: default

